export enum WaitingListNumberStatus {
  COMPLETED = 'COMPLETED',
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  JUMPED = 'JUMPED',
  MISSING = 'MISSING',
  NEXT = 'NEXT',
  PENDING = 'PENDING',
}
